# Generated by Django 3.1.3 on 2020-11-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20201119_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='distancia',
            field=models.CharField(blank=True, choices=[('lejos', 'Lejos'), ('cerca', 'Cerca')], default='lejos', max_length=5, null=True, verbose_name='Distancia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lado',
            field=models.CharField(blank=True, choices=[('izquierdo', 'Izquierda'), ('derecho', 'Derecho')], default='izquierdo', max_length=9, null=True, verbose_name='Para que ojo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lente',
            field=models.BooleanField(default=False, verbose_name='Es un lente'),
        ),
    ]
